module.exports = [
    // {
    //     title: 'Brand',
    //     options: [
    //         { key: 'MX', label: 'MEILUX' },
    //         { key: 'FS', label: 'FIRESTAR' },
    //         { key: 'PM', label: 'PROMAT' },
    //         { key: 'KF', label: 'KNAUF' },
    //         { key: 'PH', label: 'PROMATECT-H' },
    //         { key: 'KS', label: 'KNAUF SUPERPANEL' },
    //         { key: 'DS', label: 'DURASTEEL' },
    //         { key: 'HT', label: 'HUNG TEAM' },
    //     ],
    // },
    // {
    //     title: 'Type',
    //     options: [
    //         { key: 'AP', label: 'ACCESS PANEL' },
    //         { key: 'MP', label: 'MULTI PANEL' },
    //         { key: 'TP', label: 'TRAP DOOR' },
    //         { key: 'WD', label: 'WINDOW' },
    //         { key: 'DR', label: 'DOOR' },
    //         { key: 'CD', label: 'COMPOSITE DOOR' },
    //         { key: 'SD', label: 'STEEL DOOR' },
    //         { key: 'SD', label: 'SLIDING DOOR' },
    //         { key: 'GD', label: 'GLASS DOOR' },
    //         { key: 'TD', label: 'TIMBER DOOR' },
    //         { key: 'XD', label: 'EXTRA LARGE DOOR' },
    //     ],
    // },
    // {
    //     title: 'FRR	',
    //     options: [
    //         { key: '000', label: '-/-/-' },
    //         { key: '0H0', label: '-/30/-' },
    //         { key: '010', label: '-/60/-' },
    //         { key: '020', label: '-/120/-' },
    //         { key: '040', label: '-/240/-' },
    //         { key: '0HH', label: '-/30/30' },
    //         { key: '01H', label: '-/60/30' },
    //         { key: '02H', label: '-/120/30' },
    //         { key: '04H', label: '-/240/30' },
    //         { key: '011', label: '-/60/60' },
    //         { key: '021', label: '-/120/60' },
    //         { key: '041', label: '-/240/60' },
    //         { key: '022', label: '-/120/120' },
    //         { key: '042', label: '-/240/120' },
    //         { key: '044', label: '-/240/240' },
    //     ],
    // },
    {
        title: 'Hinge',
        options: [
            { key: 'SF', label: 'SCREW FIXED' },
            { key: 'CH', label: 'CONCEALED HINGE' },
            { key: 'PH', label: 'PIVOT HINGE' },
            { key: 'BH', label: 'BUTT HINGE' },
            { key: 'IH', label: 'BULLET HINGE' },
            { key: 'SD', label: 'SLIDING DOOR' },
            { key: 'NA', label: 'NOT APPLICABLE' },
        ],
    },
    {
        title: 'Finishing',
        options: [
            { key: 'FRP', label: 'FIRE RATED BOARD' },
            { key: 'STL', label: 'STEEL' },
            { key: 'GLS', label: 'GLASS' },
            { key: 'MBL', label: 'MARBLE' },
            { key: 'ACL', label: 'ARCHITECTURAL CLADDING' },
            { key: 'DST', label: 'DURASTEEL' },
            { key: 'TMB', label: 'TIMBER' },
        ],
    },
    {
        title: 'Insulation',
        options: [
            { key: 30, label: '30 Mins' },
            { key: 60, label: '1 Hrs' },
            { key: 120, label: '2 Hrs' },
            { key: 240, label: '4 Hrs' },
        ],
    },
    {
        title: 'Integrity',
        options: [
            { key: 30, label: '30 Mins' },
            { key: 60, label: '1 Hrs' },
            { key: 120, label: '2 Hrs' },
            { key: 240, label: '4 Hrs' },
        ],
    },
];
